//#pragma comment(lib, "_tkinter.lib")
#pragma comment(lib, "gui.lib")
#pragma comment(lib, "Lua.lib")
#pragma comment(lib, "python3.lib")
//#pragma comment(lib, "python36.lib")
#pragma comment(lib, "tinyxmlSTL.lib")
