//#pragma comment(lib, "../lib/x64d/_tkinter.lib")
#pragma comment(lib, "../lib/x64d/gui.lib")
//#pragma comment(lib, "../lib/x64d/Lua.lib")
//#pragma comment(lib, "../lib/x64d/python3.lib")
//#pragma comment(lib, "../lib/x64d/python36.lib")
#pragma comment(lib, "../lib/x64d/tinyxmlSTL.lib")
#pragma comment(lib, "../lib/x64d/ziputil.lib")
#pragma comment(lib, "../lib/x64d/lib_json.lib")
